name: bldrs_keywords
description: assets and classes of bldrs keywords and specs
version: 0.0.1
publish_to: none
homepage: https://github.com/RagehAz/bldrs_keywords.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/keywords/
    - lib/assets/specs/
